services:
  api1:
    build: .
    container_name: rinha-api-1
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.625"
          memory: "170MB"
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080

  api2:
    build: .
    container_name: rinha-api-2
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.625"
          memory: "170MB"
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "10MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
