services:
  api1:
    build: .
    container_name: rinha-api-1
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/rinha
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080

  api2:
    build: .
    container_name: rinha-api-2
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/rinha
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinha
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=64MB
      -c work_mem=1MB
      -c maintenance_work_mem=32MB
      -c effective_cache_size=128MB
      -c max_parallel_workers=2
      -c max_worker_processes=4
      -c synchronous_commit=off
      -c wal_compression=on
      -c autovacuum=off
      -c fsync=off
      -c full_page_writes=off
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    cpuset: "1"
    restart: unless-stopped
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  pg-data:
