services:
  api1:
    build: .
    container_name: rinha-api-1
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=rinha
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080

  api2:
    build: .
    container_name: rinha-api-2
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=rinha
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinha
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=32MB
      -c work_mem=512kB
      -c maintenance_work_mem=16MB
      -c effective_cache_size=64MB
      -c max_parallel_workers=0
      -c max_worker_processes=2
      -c synchronous_commit=off
      -c wal_compression=on
      -c autovacuum_max_workers=1
      -c autovacuum_naptime=20s
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    networks:
      - backend
    cpuset: "1"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  pg-data:
